language: node_js
node_js:
  - "12"
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: 0BxL/gSENRNqxgZUX3149a9Tv40jdyd3UFUgCp4xmyMH2ju53MPYynecauU3mgErPHn9ovLvFYuK92f5IfIwOS/CblozJUO4vg8fQZ8Dsmh/MZ+afReFUkMAIqDexEbp4JAC8H3tRqyMLejO+rmr+q0sWLyOLdej1mbEgCLYsD1mZ1F1zqBD7xZ2m8dhzybpG2LJzPuQZ1I5I2ReoX3St9tCRgUdbj78Fupxt635Cj4yA5tHYWXq9At6tvzQFHUzIumbYHXEEtzDWSlQ7GKmkiNzgblk7/3XL/j456c+KgDKjH8EZFHMRJb79bp1qRFtAbOBGia4dDvYNWXQoC5+Fw2sIpijn/JP6+BtmSveCHccSAGSnf9ZOWeny3ngFi8JdYucs0fAc79dp1be7n+7clVq2XyBWdF8CnFbtzUhDoyjhR2rbD1JiltFR9Jy9amXwkKJT6RGlKqOQud44Pwcs9vk2wmCuEV199W1xdM4VhqkXO1x1/+FmjKFmagZ/w2bUTp4f3+SzwNtWQBwErtvGL7T6tP3EKxrMkS2XYFzj5ClyhZXEGC9PNqq5pLbEEKIv874VGexvhgPtXgIZ5ImncTZ3f86Jdp2K+3NgRXIxUjRnHNOa7ru0NiY1ii4CaoffwDMeuNYgUukZy8jrU/bnfd+FsXJDKf1eT1HQu7CmY4=
  app: banking-nest-heroku-el
notifications:
  email:
    on_failure: change
    on_success: change
