language: node_js
node_js:
  - "12"
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: ABZDJKJWZ7JIcbKotFCkA6eO5CnPaZlOXZx6BpF8QdhGqbq5E7q3dujsaW1pgRBPH3hxBgRi6uSmEG9nEHU84+ptjbTjYseFko5TKpIbNjEXzbXez4vxTrk1aynAOXxuPxYEOLZdORsNQoa3BxYpuD757FDwBZ3yB7U6MwlHFP44ISdyr/qOI8xCgs9qSiSD3fRZ0XPnMdfDtB99y7Wz0a7UNPbUoTK3OggbXIbxeSrK++uKvh22u6YWPXPFVrKdoJws+YrEY4bS7jA68ED6B0SjdorzC362i1Al0Ty9Qe69PJPuSn3MSXBBcwUSHUxtUNc3dZ2aTSvhBplBsJ2H+zAaxa5U64DKwbOWq9vCrcC3/fa656EKxi/YBQ12YEiRlVgX4OpAn12SxG5wfZpRctHL+B71lfme+KV6SknkUZPUm7OIrlsVMid65phUK8HXvSqwEzyYs8AX7DMPzuMYPMnLT398sXeWTEn0SGvWSxa/3Zk60Cm5FkvuGwD2C1vTctXngP77+D8kyAkZqG3pTOU8OsM2HV0B6VoDEMHw5zLwPbwcNk+YB26i4XGXYyEb+mA5S40v3GDqpCsG0LXAgBwUTkn4IRd2efyavY+wXamtkGWg9vU/dKHsWiw7wGrR/XNKgIb2kBm6dInnAanjQnID6OZvCDeIEtzyZ0utr6o=
  app: banking-nest-heroku-el
notifications:
  email:
    on_failure: change
    on_success: change
