language: node_js
node_js:
  - "12"
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: FgSXiT8+JAGvOIjJQNskznNZU/6qlBKQk0+vi2Yrb/HfTmp7IzzKGafVnmpbO/449c/0EBl3zkcNnOXnEsdVYBmD1+dZlvJZ52c51umTaij7aclma+IEBK0N2216AVfyMbt2hp0FyPTonDsX9MusKd32zUU0355HxQMZ6whiZoV68DsHtZ1K9suCFQylSefkFMKh8Ra67gMdGndrvnqQ/0aLRBNxiYhC68yFQeJ7H96WE6PIGTxYv2l94kSbHvvrBqriB9n+3yrLlJMIzgqLb92DK2RpDi5x+9m4UcTKqfTO2Rw/Tq78wsRd3Ocdd74uAXQXqbsR2+SYT2Crci+tFa9aR9i5b9Mt/TjAGZWrZO1jHfocKFU5YcdwcD5/aoPhZYhZ1y6u4V6FbPforr/0XtTVUTpGVXMHZ3Nlml+n/zRunq/2WKsWOqFvcxaIczhiiorpDp0m2blMYrMNHl4MrraR9xpwU5M3tYeXa/N4YF4SUbdpuB1Qoe6IB4q32YYHCAG/dIQb9dqlC9GgZ/uLr0xapVmzR21m+3DjABVwmKzCRIaX05zJLpwyMsRy3TDgsJKj5iwwJoR2wS0zm7nn/OouKj4eFGPPPfV+spk0EQ6VwkOyZc6o/9mg51uK9kDRawvvQ/c1EnVdm48YQFiDuReNK8MNrdxHoowKvhcTkQ0=
  app: banking-nest-heroku-el
notifications:
  email:
    on_failure: change
    on_success: change
