language: node_js
node_js:
  - "12"
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: d7OBfjXbNgfiFXHkDNUYMSz7GFiM5EP9Z9ete46soTHYCI+wGAJltIpV4Mqa1opWG3EoNGd09UesjT88I2xNADo9EnpIbJR49SOAQkfQnbXJR593bQRytm4FW9L0rL28LBRwoE8zWb/M2sbyyM9cMeEwYQdpLgOeblJ6m6NTWjPQzIaDgRQ8B0MyXSFTBorK0ZchXWwvES+gwb6er0A27ivTbFSR7Ep5zSUAMm5OuOzQBza1IGx5DL1G9UBX7c20QjaQX8yB4BXppUYAwjRpWgGWDv7dfnRBT/mHcKOU30LwIDv/721x99eKASaYpc77UPy4Jn7Y6t0BdxGfYnzE0agFzTLDKDuyek0ol01z2i3rML4x1+0MKJcl08FpXMfb3LT20Lvq7cHJKTvglOGY1SIr0aXXF+T77Dww3Gxcfyy7qvd9BekPENt/0hM2xlMC+K+Ro5QYP38S4bP6T4fWaOt0Fpv/APjKWmRF9F1t1ftXpzWXv5u9byg6dz0tgIU33yfsBBcxTHEeNMXLeoV/aXMU7px5vkOwu93sR2NtfdOnDaiZEAHZjT28RK7qWjXc8BCxfQswj0U77xa/BvHWor4DzB31aBTjEpDu6VsFEHetqmqVo/cBDU2T3+heKi39+bQYGNObCHS5tF+UNVZ+6CPqNZVawnEosWr+nWPo4ws=
  app: banking-nest-heroku-el
notifications:
  email:
    on_failure: change
    on_success: change
