language: node_js
node_js:
- '12'
branches:
  only:
  - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: pxR4O/x93m0RNCw0E6FmnsHq24GjLREIeZrvxYijOUGqhpU+JTqKLbP1QevoyV8DKe+5+BKynDVh5OlFsvaudOL9d8yn3FQ9gfHUpGVr4SE43VN+YjtNL2+cQpTgWF/0teCiT2VkHtc9Ipm8rECRIUS0D05Gzsqi9L3Yp8Lx1F5T4Ca0tsStT8Rn4p6SDqLYAGvKE2Yg7JbrAOlLcqsZ74xU9DN0HDslZo9FN/c2ECteJmjVVZ4HUSNT1QT5B/sTRgM3DtUVTfT7tUc+g8WC5840QM67QTjqFTaAn8Ghqdo0sTRTABQe97AotJP/RErzumw0pVn0NViesAdNMysGfx1Q7YDVxbHy8H8qjd8oJi/nDycu7Pjuh5qWwM8nxQiWJze+qbwT0ge6lqaGr4q2JRsJGliUtxh/O6I7NWFPhEoLSY1KPoqO1ULeERUsUmeN5HFE08CvYZC8m9I+Q3esSAlvouK6deXwogIOlysR7AbdwnXT6rQKhmW1hbg17YNQBDRRr6JG4ckaAR9NZ7MysMTYVmoa5viA2iaVtuRbRcmA4sBc938zyn3PGehIqtTV+qVIuY2GBGdHvuiq/W5VxvtZkZ3A33Ox7Kh0pT+LBPMbJ9hElDDEvn4OBxRi3vz83W/zZWhfMXwgx/f6ipxGRk7+GpIJxrbiU4m7nv4sHr8=
  app: banking-nest-heroku-el
notifications:
  email:
    on_failure: change
    on_success: change
