language: node_js
node_js:
- '12'
branches:
  only:
  - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: nCrsMk7y9Vqo4++YuzAkTxASBJamt+miNjx8JN9e3AdZi3+mdbEHIAcUPpH+YP0RzaiQg/7HPPJF/sZfqb7NQVikwS/31qsDf89coDy+J78A71accULUZIo5hjp3dns94qr1D/1w8p26rSjh1LQY/HukZHyh5XM+wJ7LbxUu+Uhy3im3MR04iLawmyRuAQA3jf40e3EHEdsJ27Yf2F5AKhkficCA9qLi8+YynCSXi02jEBHgbCuR4CmHCrOfqNCYTJqm8WctTXEw/uxfHHxmnL3S1Y7xwsI4ei0/kCatyF/wJvEvh9o2z1zlEsEXOHK3ry6LPhtHImheSifE2JYMWDSvSVwPukwae0l6iet1AFOCU5SaJdxdO942tYkuIRGe/Sa/U0bxPV/BARrV6BJ7H1DzLEHbUp7IUKCG9Q7z8IGpzOt0QbL/nHaT+FE97vPu7GbVTUag4glJ5jKzEXburi/+14VxZl4jFh3x0mA1Sml2HQmiSOvO/dkFLA9B5UeNQPCGOGNjvYLMn9pCNwgkmGS0Ri7gVvfNeSjgyT72JW4dIeRIctgxvfyMpivqjh7u3xKRU1hrDdLd0jezlhAwoiRGJYJEB7aJW7RD3hQ0a+BQp+kN0sh2I0UtEbvV4f+m2k+TXDomiCQpCLmwMZh3DO1NLiq/xMksMxeuG5pj6HI=
  app: banking-nest-heroku-el
notifications:
  email:
    on_failure: change
    on_success: change
