language: node_js
node_js:
  - "12"
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: KuUNfnlNff/E0/4ivToUEIkhocP5PEOjSIcfV8OzzGLlmDQPhEDQu3axnx1cd/eO4DmJWyFcltZRAhehxXXxMJhpqliyNDiJgWmsu2gkY4StJPEyn3/bTYZBaSTfC84dX+rmnibrBqCPaB5j0CBLajr5pVLH3jOTfgse6AF+uOSwPXR+KfNgE4gT1KX9BoWrH7MOv5wECzAWF72IXBgbgLpacpa7eoiQol/VvOVmSiJhsPJEiIWQJr/wCzIS5IrsXu6Wwqp2Venje3SgV1rYvJczDBSVTv+oMbp/0Tfhtnkr41ocU7gB5q7WHqnXKfS//xnBb4oabzqPgvIbrnwc3z5+x5Pp/8vkVmdm1/pm0UkBc+9KYlUC1Aql+6gdToi18sh6L5ni3F1h2eLpWWFzEYkweCnGovTGY0A9OznvU5aem8LdKKTkPKmHMX2ohTVao6qnrPHYQOFfxui78HKhzH+MrSVzfwRc9gW+wyrHx1lPqBVRynvCtUUSegl6QiCx9EPTII5p5GMppBuQrMBDk/3MK0z+cl0D9cXWBQF4NloPJpXTvuUJ8rBTRcI/TyIXCUZEvh9D0aTuDUmtOSNPxqJHX9DFyUdGuAfZs0L6t/ARh08X05blq6jQaFE6Hena77tw6Cju0U0v/R6qSOGi8zJHhWZvbRbT4Dq1xDgR+GE=
  app: banking-nest-heroku-el
notifications:
  email:
    on_failure: change
    on_success: change
